apartments = [
    {
        "id": 1,
        "rooms": 2,
        "surface": 45,
        "price": 200000,
        "floor": 1,
        "favorite": True,
        "available": True,
    },
    {
        "id": 2,
        "rooms": 3,
        "surface": 60,
        "price": 300000,
        "floor": 2,
        "favorite": False,
        "available": True,
    },
    {
        "id": 3,
        "rooms": 4,
        "surface": 85,
        "price": 450000,
        "floor": 3,
        "favorite": True,
        "available": False,
    },
    {
        "id": 4,
        "rooms": 1,
        "surface": 35,
        "price": 150000,
        "floor": 0,
        "favorite": False,
        "available": True,
    },
    {
        "id": 5,
        "rooms": 2,
        "surface": 50,
        "price": 250000,
        "floor": 1,
        "favorite": True,
        "available": True,
    },
    {
        "id": 6,
        "rooms": 3,
        "surface": 75,
        "price": 400000,
        "floor": 2,
        "favorite": False,
        "available": False,
    },
    {
        "id": 7,
        "rooms": 5,
        "surface": 120,
        "price": 600000,
        "floor": 5,
        "favorite": True,
        "available": True,
    },
    {
        "id": 8,
        "rooms": 2,
        "surface": 40,
        "price": 180000,
        "floor": 0,
        "favorite": False,
        "available": True,
    },
    {
        "id": 9,
        "rooms": 1,
        "surface": 30,
        "price": 120000,
        "floor": 0,
        "favorite": False,
        "available": False,
    },
    {
        "id": 10,
        "rooms": 3,
        "surface": 65,
        "price": 350000,
        "floor": 3,
        "favorite": True,
        "available": True,
    },
]
