apartments = [
    {
        "id": 1,
        "rooms": 2,
        "surface": 45,
        "price": 200000,
        "floor": 1,
        "favorite": True,
    },
    {
        "id": 2,
        "rooms": 3,
        "surface": 60,
        "price": 300000,
        "floor": 2,
        "favorite": False,
    },
    {
        "id": 3,
        "rooms": 4,
        "surface": 85,
        "price": 450000,
        "floor": 3,
        "favorite": True,
    },
    {
        "id": 4,
        "rooms": 1,
        "surface": 35,
        "price": 150000,
        "floor": 0,
        "favorite": False,
    },
    {
        "id": 5,
        "rooms": 2,
        "surface": 50,
        "price": 250000,
        "floor": 1,
        "favorite": True,
    },
    {
        "id": 6,
        "rooms": 3,
        "surface": 75,
        "price": 400000,
        "floor": 2,
        "favorite": False,
    },
    {
        "id": 7,
        "rooms": 5,
        "surface": 120,
        "price": 600000,
        "floor": 5,
        "favorite": True,
    },
    {
        "id": 8,
        "rooms": 2,
        "surface": 40,
        "price": 180000,
        "floor": 0,
        "favorite": False,
    },
    {
        "id": 9,
        "rooms": 1,
        "surface": 30,
        "price": 120000,
        "floor": 0,
        "favorite": False,
    },
    {
        "id": 10,
        "rooms": 3,
        "surface": 65,
        "price": 350000,
        "floor": 3,
        "favorite": True,
    },
    {
        "id": 11,
        "rooms": 4,
        "surface": 90,
        "price": 470000,
        "floor": 4,
        "favorite": True,
    },
    {
        "id": 12,
        "rooms": 1,
        "surface": 25,
        "price": 100000,
        "floor": -1,
        "favorite": False,
    },
    {
        "id": 13,
        "rooms": 3,
        "surface": 70,
        "price": 370000,
        "floor": 2,
        "favorite": True,
    },
    {
        "id": 14,
        "rooms": 2,
        "surface": 55,
        "price": 260000,
        "floor": 1,
        "favorite": False,
    },
    {
        "id": 15,
        "rooms": 4,
        "surface": 95,
        "price": 500000,
        "floor": 4,
        "favorite": True,
    },
    {
        "id": 16,
        "rooms": 2,
        "surface": 48,
        "price": 230000,
        "floor": 1,
        "favorite": False,
    },
    {
        "id": 17,
        "rooms": 5,
        "surface": 130,
        "price": 700000,
        "floor": 6,
        "favorite": True,
    },
    {
        "id": 18,
        "rooms": 3,
        "surface": 68,
        "price": 340000,
        "floor": 3,
        "favorite": False,
    },
    {
        "id": 19,
        "rooms": 2,
        "surface": 42,
        "price": 190000,
        "floor": 0,
        "favorite": True,
    },
    {
        "id": 20,
        "rooms": 4,
        "surface": 80,
        "price": 420000,
        "floor": 3,
        "favorite": False,
    },
]
